Repository openshmem-org/specification, pull requests merged in 2019-09, with the labels that each got.

#290 Fix example intro affected by Fortran removal
  content/shmem_ptr.tex
Labels: DocumentEdit

#267 Wait/Test Clarifications
  content/backmatter.tex
  content/memory_model.tex
  content/shmem_test.tex
  content/shmem_test_all.tex
  content/shmem_test_any.tex
  content/shmem_test_some.tex
  content/shmem_wait_until.tex
  content/shmem_wait_until_all.tex
  content/shmem_wait_until_any.tex
  content/shmem_wait_until_some.tex
  example_code/shmem_test_any_example.c
  example_code/shmem_test_example1.c
  example_code/shmem_test_some_example.c
  example_code/shmem_wait3_example.c
  example_code/shmem_wait_until_all.c
  example_code/shmem_wait_until_any_all2all_sum.c
  example_code/shmem_wait_until_some_all2all_sum.c
Labels: HadReading, PendingBallot, Ratified, SpecialBallot, SpecialBallotAccepted

#275 Add support for Blocking and Non-blocking put-with-signal
  content/backmatter.tex
  content/library_constants.tex
  content/p2p_sync_intro.tex
  content/shmem_fence.tex
  content/shmem_put_signal.tex
  content/shmem_put_signal_nbi.tex
  content/shmem_quiet.tex
  content/shmem_signal_fetch.tex
  content/shmem_signal_wait_until.tex
  content/shmem_wait_until.tex
  example_code/shmem_put_signal_example.c
  main_spec.tex
  utils/defs.tex
Labels: HadReading, PendingBallot, Ratified, SpecialBallot, SpecialBallotAccepted

#274 Add wait/test all/any/some API with "vector" cmp_values
  content/programming_model_overview.tex
  content/shmem_test_all.tex
  content/shmem_test_all_vector.tex
  content/shmem_test_any.tex
  content/shmem_test_any_vector.tex
  content/shmem_test_some.tex
  content/shmem_test_some_vector.tex
  content/shmem_wait_until_all.tex
  content/shmem_wait_until_all_vector.tex
  content/shmem_wait_until_any.tex
  content/shmem_wait_until_any_vector.tex
  content/shmem_wait_until_some.tex
  content/shmem_wait_until_some_vector.tex
  example_code/shmem_wait_until_any_vector.c
  main_spec.tex
Labels: HadReading, HasChangeMarkers, PendingBallot, Ratified, SectionCommittee, SpecialBallot, SpecialBallotAccepted
