Repository openshmem-org/specification, pull requests merged in 2019-10, with the labels that each got.

#300 Remove change markers
  content/library_constants.tex
  content/shmem_put_signal.tex
  content/shmem_put_signal_nbi.tex
  content/shmem_signal_fetch.tex
  content/shmem_signal_wait_until.tex
  main_spec.tex
Labels: DocumentEdit

#297 Teams Proposal
  .gitignore
  content/backmatter.tex
  content/collective_intro.tex
  content/coverpage.tex
  content/library_constants.tex
  content/library_handles.tex
  content/rma_intro.tex
  content/shmem_alltoall.tex
  content/shmem_alltoalls.tex
  content/shmem_barrier.tex
  content/shmem_barrier_all.tex
  content/shmem_broadcast.tex
  content/shmem_calloc.tex
  content/shmem_collect.tex
  content/shmem_ctx_create.tex
  content/shmem_ctx_destroy.tex
  content/shmem_ctx_get_team.tex
  content/shmem_finalize.tex
  content/shmem_malloc.tex
  content/shmem_reductions.tex
  content/shmem_sync.tex
  content/shmem_sync_all.tex
  content/shmem_team_config_t.tex
  content/shmem_team_create_ctx.tex
  content/shmem_team_destroy.tex
  content/shmem_team_get_config.tex
  content/shmem_team_my_pe.tex
  content/shmem_team_n_pes.tex
  content/shmem_team_split_2d.tex
  content/shmem_team_split_strided.tex
  content/shmem_team_translate_pe.tex
  content/teams_intro.tex
  example_code/shmem_alltoall_example.c
  example_code/shmem_alltoalls_example.c
  example_code/shmem_broadcast_example.c
  example_code/shmem_collect_example.c
  example_code/shmem_reduce_example.c
  example_code/shmem_sync_example.c
  example_code/shmem_team_context.c
  example_code/shmem_team_split_2D.c
  example_code/shmem_team_split_strided.c
  example_code/shmem_team_translate_pe.c
  main_spec.tex
  utils/defs.tex
  utils/packages.tex
Labels: Ratified

#247 Add support for NBI fetching AMOs
  .gitignore
  content/backmatter.tex
  content/p2p_sync_intro.tex
  content/shmem_atomic_compare_swap_nbi.tex
  content/shmem_atomic_fetch_add_nbi.tex
  content/shmem_atomic_fetch_and_nbi.tex
  content/shmem_atomic_fetch_inc_nbi.tex
  content/shmem_atomic_fetch_nbi.tex
  content/shmem_atomic_fetch_or_nbi.tex
  content/shmem_atomic_fetch_xor_nbi.tex
  content/shmem_atomic_swap_nbi.tex
  content/shmem_fence.tex
  content/shmem_get_nbi.tex
  content/shmem_put_nbi.tex
  content/shmem_put_signal.tex
  content/shmem_put_signal_nbi.tex
  content/shmem_quiet.tex
  main_spec.tex
Labels: DocumentEdit, HadReading, HasChangeMarkers, PendingBallot, Ratified, SpecialBallot, SpecialBallotAccepted

#299 Add change-log entry for the wait/test "vector" API
  content/backmatter.tex
Labels: DocumentEdit
