Repository openshmem-org/specification, pull requests merged in 2020-01, with the labels that each got.

#291 Clarify reduction src/dest overlap text
  content/shmem_reductions.tex
Labels: HadReading, PendingBallot, Ratified, SpecialBallot, SpecialBallotAccepted

#304 Rewriting annex - interoperability with other programming models
  content/backmatter.tex
  content/interoperability.tex
  example_code/hybrid_mpi_mapping_id.c
  example_code/hybrid_mpi_mapping_id_shmem_comm.c
Labels: HadReading, Ratified, SpecialBallot, SpecialBallotAccepted

#306 Define atomicity domains w.r.t. teams
  content/memory_model.tex
  example_code/amo_scenario_1.c
  example_code/amo_scenario_2.c
  example_code/amo_scenario_3.c
  example_code/amo_scenario_4.c
Labels: HadReading, PendingBallot, Ratified

#305 Revise error handling w.r.t. invalid teams
  content/collective_intro.tex
  content/shmem_ctx_get_team.tex
  content/shmem_team_create_ctx.tex
  content/shmem_team_destroy.tex
  content/shmem_team_get_config.tex
  content/shmem_team_my_pe.tex
  content/shmem_team_n_pes.tex
  content/shmem_team_split_2d.tex
  content/shmem_team_split_strided.tex
  content/shmem_team_translate_pe.tex
Labels: HadReading, PendingBallot, Ratified, SpecialBallot, SpecialBallotAccepted

#327 Remove change highlighting from #304
  content/backmatter.tex
Labels: DocumentEdit
