Repository openshmem-org/specification, pull requests merged in 2024-08, with the labels that each got.

#523 Remove /newline shmem_malloc_hints table, prevents compilation
  content/shmem_malloc_hints.tex
Labels: DocumentEdit

#517 Clarify memory managment routines are world-collective
  content/backmatter.tex
  content/shmem_align.tex
  content/shmem_free.tex
  content/shmem_malloc.tex
  content/shmem_malloc_hints.tex
  content/shmem_realloc.tex
Labels: Ratified, HadReading

#519 Teams: clarify behavior of split ops with strides <= 0
  content/backmatter.tex
  content/shmem_team_split_strided.tex
Labels: Ratified, HadReading

#520 team_get_config: clarify config_mask == 0 and config == NULL cases
  content/backmatter.tex
  content/shmem_team_get_config.tex
Labels: Ratified, HadReading

#521 team_get_config: return the *current* config values
  content/backmatter.tex
  content/shmem_team_get_config.tex
Labels: Ratified, HadReading

#488 Add inclusive and exclusive scan (prefix sum) operations
  content/shmem_scan.tex
  example_code/shmem_scan_example.c
  main_spec.tex
Labels: Ratified, HadReading, NeedsChangeLogEntry
